"""Initial Migration

Revision ID: 99ab0e79d490
Revises: 80067999a5e9
Create Date: 2019-09-26 17:59:08.785264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ab0e79d490'
down_revision = '80067999a5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'likes')
    op.drop_column('blogs', 'dislikes')
    # ### end Alembic commands ###
