"""Initial Migration

Revision ID: f845fd10ad5d
Revises: 72336e1637cb
Create Date: 2019-09-27 16:20:41.108200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f845fd10ad5d'
down_revision = '72336e1637cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'dislikes')
    op.drop_column('blogs', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
